# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # configure hostmanager
    config.hostmanager.enabled = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    # puppetmaster on Centos 7
    config.vm.define "puppet" do |puppet|
        config.vm.provider "virtualbox" do |v|
            v.memory = 2048
        end

        puppet.vm.box = "centos/7"
        puppet.vm.hostname = "puppet.example.com"
        puppet.vm.network :private_network, ip: "10.0.20.10"
        puppet.hostmanager.aliases = %w(puppet)
        puppet.vm.synced_folder ".", "/home/vagrant/sync"
        puppet.vm.synced_folder "../code", "/puppet_code"
        puppet.vm.synced_folder "../puppetserver", "/puppet_puppetserver"
        puppet.vm.provision "shell", :path => "puppet.sh"
    end

    # puppet agent1 on Centos 7
    config.vm.define "agent1" do |agent1|
        agent1.vm.box = "centos/7"
        agent1.vm.hostname = "agent1.example.com"
        agent1.vm.network :private_network, ip: "10.0.20.11"
        agent1.hostmanager.aliases = %w(agent1)
        agent1.vm.provision "shell", :path => "agent1.sh"
    end

    # puppet agent2 on Debian Jessie
    config.vm.define "agent2" do |agent2|
        agent2.vm.box = "debian/jessie64"
        agent2.vm.hostname = "agent2.example.com"
        agent2.vm.network :private_network, ip: "10.0.20.12"
        agent2.hostmanager.aliases = %w(agent2)
        agent2.vm.provision "shell", :path => "agent2.sh"
    end

    # puppet agent2 on Windows2012 R2
    config.vm.define "agent3" do |agent3|
        agent3.vm.box = "devopsguys/Windows2012R2Eval"
        agent3.vm.hostname = "agent3.example.com"
        agent3.vm.network :private_network, ip: "10.0.20.13"
        agent3.hostmanager.aliases = %w(agent3)
        agent3.vm.provision "shell", :path => "agent3.ps1"
    end
end
